name: deploy
run-name: ${{github.actor}} deploy app to the server
on:
  push:
    branches:
      - env/prod
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.0
        env:
          ENV_FILE: ${{secrets.ENV_FILE}}
        with:
          command_timeout: 200m
          host: elsombrero.pro
          username: elsombrero
          port: 22
          envs: ENV_FILE
          password: ${{secrets.SSH_PASSWORD}}
          script: |
            cd deploy
            mkdir portal
            cd portal
            git clone https://github.com/elsombrero-local/web-portal.git .
            git checkout env/prod
            git branch
            echo -e $ENV_FILE
            echo -e $ENV_FILE > .env
            docker-compose up -d --build --force-recreate app
            cd ..
            rm -rf portal